import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ZENVY | Dashboard ",
  description: "Generated by create next app",
};

export default function DashboardPage() {
  return (
    <section className="h-screen bg-amber-100">
      Dashboard
    </section>
  );
}
