import CartPageComponent from '@/components/pages/cart/CartPageComponent';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "ZENVY | Shopping Cart ",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <CartPageComponent/>
    </div>
  );
};

export default page;