import { Product } from "./types";
const product_list: Product[] = [
  {
    id: "prod_001",
    productName: "Classic Slim Fit Tee",
    slug: "classic-slim-fit-tee",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 20.0,
    discountPercent: 7,
    finalPrice: 18.6,
    thumbnail: "products/product_image.png",
    availableColors: [
      { color: "Navy Blue", colorHex: "#1B2A4A" },
      { color: "Red", colorHex: "#E63946" },
    ],
    availableSizes: ["S", "M", "L", "XL"],
  },
  {
    id: "prod_002",
    productName: "Heavyweight Oversized Tee",
    slug: "heavyweight-oversized-tee",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 28.0,
    discountPercent: 0,
    finalPrice: 28.0,
    thumbnail: "products/product_image.png",
    availableColors: [
      { color: "Cream", colorHex: "#F5F5DC" },
      { color: "Charcoal", colorHex: "#36454F" },
    ],
    availableSizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "prod_003",
    productName: "Graphic Vintage Rock Tee",
    slug: "graphic-vintage-rock-tee",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 32.0,
    discountPercent: 15,
    finalPrice: 27.2,
    thumbnail: "products/product_image.png",
    availableColors: [{ color: "Washed Black", colorHex: "#212121" }],
    availableSizes: ["S", "M", "L", "XL"],
  },
  {
    id: "prod_004",
    productName: "Organic V-Neck T-Shirt",
    slug: "organic-v-neck-t-shirt",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 22.5,
    discountPercent: 10,
    finalPrice: 20.25,
    thumbnail: "products/product_image.png",
    availableColors: [
      { color: "White", colorHex: "#FFFFFF" },
      { color: "Heather Grey", colorHex: "#A9A9A9" },
    ],
    availableSizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "prod_005",
    productName: "Classic Denim Button-Down",
    slug: "classic-denim-button-down",
    category: { product: "Shirt", slug: "shirt" },
    regularPrice: 48.0,
    discountPercent: 20,
    finalPrice: 38.4,
    thumbnail: "https://cdn.store.com/shirt-denim-blue.jpg",
    availableColors: [
      { color: "Light Wash", colorHex: "#AED6F1" },
      { color: "Dark Wash", colorHex: "#2E4053" },
    ],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "prod_006",
    productName: "Linen Summer Short Sleeve",
    slug: "linen-summer-short-sleeve",
    category: { product: "Shirt", slug: "shirt" },
    regularPrice: 45.0,
    discountPercent: 5,
    finalPrice: 42.75,
    thumbnail: "https://cdn.store.com/shirt-linen-olive.jpg",
    availableColors: [
      { color: "Olive Green", colorHex: "#556B2F" },
      { color: "Oatmeal", colorHex: "#EAE6DF" },
    ],
    availableSizes: ["S", "M", "L", "XL"],
  },
  {
    id: "prod_007",
    productName: "Oxford Cotton Dress Shirt",
    slug: "oxford-cotton-dress-shirt",
    category: { product: "Shirt", slug: "shirt" },
    regularPrice: 55.0,
    discountPercent: 0,
    finalPrice: 55.0,
    thumbnail: "https://cdn.store.com/shirt-oxford-sky.jpg",
    availableColors: [
      { color: "Sky Blue", colorHex: "#87CEEB" },
      { color: "White", colorHex: "#FFFFFF" },
    ],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "prod_008",
    productName: "Flannel Plaid Lumberjack Shirt",
    slug: "flannel-plaid-lumberjack-shirt",
    category: { product: "Shirt", slug: "shirt" },
    regularPrice: 42.0,
    discountPercent: 12,
    finalPrice: 36.96,
    thumbnail: "https://cdn.store.com/shirt-flannel-red.jpg",
    availableColors: [
      { color: "Red Plaid", colorHex: "#900C3F" },
      { color: "Green Plaid", colorHex: "#196F3D" },
    ],
    availableSizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "prod_009",
    productName: "Slim Fit Stretch Jeans",
    slug: "slim-fit-stretch-jeans",
    category: { product: "Jeans", slug: "jeans" },
    regularPrice: 65.0,
    discountPercent: 10,
    finalPrice: 58.5,
    thumbnail: "https://cdn.store.com/jeans-slim-indigo.jpg",
    availableColors: [
      { color: "Indigo", colorHex: "#4B0082" },
      { color: "Jet Black", colorHex: "#0A0A0A" },
    ],
    availableSizes: ["30", "32", "34", "36"],
  },
  {
    id: "prod_010",
    productName: "Relaxed Straight Leg Denim",
    slug: "relaxed-straight-leg-denim",
    category: { product: "Jeans", slug: "jeans" },
    regularPrice: 58.5,
    discountPercent: 0,
    finalPrice: 58.5,
    thumbnail: "https://cdn.store.com/jeans-straight-stone.jpg",
    availableColors: [{ color: "Stone Wash", colorHex: "#7FB3D5" }],
    availableSizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "prod_011",
    productName: "Distressed Skinny Moto Jeans",
    slug: "distressed-skinny-moto-jeans",
    category: { product: "Jeans", slug: "jeans" },
    regularPrice: 75.0,
    discountPercent: 25,
    finalPrice: 56.25,
    thumbnail: "https://cdn.store.com/jeans-skinny-grey.jpg",
    availableColors: [{ color: "Smoke Grey", colorHex: "#626567" }],
    availableSizes: ["30", "32", "34"],
  },
  {
    id: "prod_012",
    productName: "Essential Fleece Pullover Hoodie",
    slug: "essential-fleece-pullover-hoodie",
    category: { product: "Hoodie", slug: "hoodie" },
    regularPrice: 49.99,
    discountPercent: 5,
    finalPrice: 47.49,
    thumbnail: "https://cdn.store.com/hoodie-pullover-grey.jpg",
    availableColors: [
      { color: "Heather Grey", colorHex: "#BDC3C7" },
      { color: "Black", colorHex: "#1C2833" },
      { color: "Forest Green", colorHex: "#1E4620" },
    ],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "prod_013",
    productName: "Full-Zip Streetwear Hoodie",
    slug: "full-zip-streetwear-hoodie",
    category: { product: "Hoodie", slug: "hoodie" },
    regularPrice: 60.0,
    discountPercent: 18,
    finalPrice: 49.2,
    thumbnail: "https://cdn.store.com/hoodie-zip-tan.jpg",
    availableColors: [
      { color: "Desert Tan", colorHex: "#D2B48C" },
      { color: "Burgundy", colorHex: "#800020" },
    ],
    availableSizes: ["M", "L", "XL"],
  },
  {
    id: "prod_014",
    productName: "Colorblock Crop Hoodie",
    slug: "colorblock-crop-hoodie",
    category: { product: "Hoodie", slug: "hoodie" },
    regularPrice: 45.0,
    discountPercent: 0,
    finalPrice: 45.0,
    thumbnail: "https://cdn.store.com/hoodie-crop-pastel.jpg",
    availableColors: [{ color: "Pastel Pink/White", colorHex: "#FADBD8" }],
    availableSizes: ["XS", "S", "M", "L"],
  },
  {
    id: "prod_015",
    productName: "Heavyweight Thermal Winter Hoodie",
    slug: "heavyweight-thermal-winter-hoodie",
    category: { product: "Hoodie", slug: "hoodie" },
    regularPrice: 85.0,
    discountPercent: 10,
    finalPrice: 76.5,
    thumbnail: "https://cdn.store.com/hoodie-thermal-navy.jpg",
    availableColors: [{ color: "Midnight Navy", colorHex: "#0E1A35" }],
    availableSizes: ["S", "M", "L", "XL", "XXL", "3XL"],
  },
];

export const shortProductList: Product[] = [
  {
    id: "prod_001",
    productName: "Classic Slim Fit Tee",
    slug: "classic-slim-fit-tee",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 20.0,
    discountPercent: 7,
    finalPrice: 18.6,
    thumbnail: "/products/product_image.png",
    availableColors: [
      { color: "Navy Blue", colorHex: "#1B2A4A" },
      { color: "Red", colorHex: "#E63946" },
    ],
    availableSizes: ["S", "M", "L", "XL"],
  },
  {
    id: "prod_002",
    productName: "Heavyweight Oversized Tee",
    slug: "heavyweight-oversized-tee",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 28.0,
    discountPercent: 0,
    finalPrice: 28.0,
    thumbnail: "/products/product_image.png",
    availableColors: [
      { color: "Cream", colorHex: "#F5F5DC" },
      { color: "Charcoal", colorHex: "#36454F" },
    ],
    availableSizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "prod_003",
    productName: "Graphic Vintage Rock Tee",
    slug: "graphic-vintage-rock-tee",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 32.0,
    discountPercent: 15,
    finalPrice: 27.2,
    thumbnail: "/products/product_image.png",
    availableColors: [{ color: "Washed Black", colorHex: "#212121" }],
    availableSizes: ["S", "M", "L", "XL"],
  },
  {
    id: "prod_004",
    productName: "Organic V-Neck T-Shirt",
    slug: "organic-v-neck-t-shirt",
    category: { product: "T-Shirt", slug: "t-shirt" },
    regularPrice: 22.5,
    discountPercent: 10,
    finalPrice: 20.25,
    thumbnail: "/products/product_image.png",
    availableColors: [
      { color: "White", colorHex: "#FFFFFF" },
      { color: "Heather Grey", colorHex: "#A9A9A9" },
    ],
    availableSizes: ["XS", "S", "M", "L", "XL"],
  },
];
