import Banner from "@/components/pages/home/Banner";
import BrandsSection from "@/components/pages/home/BrandsSection";
import TopLists from "@/components/pages/home/TopLists";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ZENVY | Home ",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <section>
      {/* Banner Section */}
      <Banner />

<BrandsSection />
      {/* Top Lists Section */}
      <TopLists />
    </section>
  );
}
