import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ZENVY | Home ",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <section>
      Home
    </section>
  );
}
